src/models/library.py
from lib.extensions import db
from datetime import datetime


class Collection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)
    description = db.Column(db.Text(1024))
    games = db.relationship('Game', backref='collection')

    def __repr__(self):
        return f'{self.name}'


class Genre(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))
    games = db.relationship('Game', backref='genre')
    legacy_id = db.Column(db.Integer, unique=True)

    def __repr__(self):
        return f'{self.name}'


class Platform(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    emulator = db.Column(db.Boolean, default=0)
    launcher = db.Column(db.String(128))
    name = db.Column(db.String(128), unique=True)
    ra_core = db.Column(db.String(128))
    slug = db.Column(db.String(128), unique=True)
    legacy_id = db.Column(db.Integer, unique=True)
    games = db.relationship('Game', backref='platform')

    def __repr__(self):
        return f'{self.name}'


class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    alt_title = db.Column(db.String(128), unique=True)
    archived = db.Column(db.Boolean, default=0)
    co_op = db.Column(db.Boolean, default=0)
    collection_id = db.Column(db.Integer, db.ForeignKey('collection.id'))
    controller_support = db.Column(db.Boolean, default=0)
    date_added = db.Column(db.DateTime, default=datetime.utcnow)
    date_modified = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.Text(8192))
    developer = db.Column(db.String(128))
    esrb = db.Column(db.String(4))
    favorite = db.Column(db.Boolean, default=0)
    filename = db.Column(db.String(128), nullable=False, unique=True)
    genre_id = db.Column(db.Integer, db.ForeignKey('genre.id'))
    gpu = db.Column(db.String(64))
    hdd = db.Column(db.String(64))
    last_played = db.Column(db.DateTime)
    mod = db.Column(db.String(64))
    notes = db.Column(db.Text(8192))
    online_multiplayer = db.Column(db.Boolean, default=0)
    operating_system = db.Column(db.String(64))
    platform_id = db.Column(db.Integer, db.ForeignKey('platform.id'))
    play_count = db.Column(db.Integer, default=0)
    players = db.Column(db.Integer, db.CheckConstraint('players >= 1 AND players <= 64'), default=1)
    processor = db.Column(db.String(64))
    publisher = db.Column(db.String(128))
    ram = db.Column(db.String(64))
    region = db.Column(db.String(2))
    save_path = db.Column(db.String(256))
    steam_id = db.Column(db.Integer)
    store = db.Column(db.String(32))
    tags = db.Column(db.String(128))
    title = db.Column(db.String(128), nullable=False)
    translation = db.Column(db.Boolean, default=0)
    year = db.Column(db.Integer, db.CheckConstraint('year >= 1948 AND players < 9999'))

    def __repr__(self):
        return f'{self.title}'

    def slug(self):
        slug = self.filename.split('.')[0]
        return slug

    def sort_title(self):
        if self.title.endswith(', The') or self.title.endswith(', A'):
            x, y = self.title.split(', ')
            sort_title = str(y + ' ' + x)
        else:
            sort_title = self.title
        return sort_title

    def tag_array(self):
        tag_array = []
        tag_string = self.tags.split(',')
        for t in tag_string:
            tag_array.append(t)
        return tag_array

src/forms/library.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, HiddenField, IntegerField, SelectField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, NumberRange, Optional


# FORMS
class GameForm(FlaskForm):
    alt_title = StringField(validators=[Length(max=128), Optional()])
    archived = BooleanField()
    co_op = BooleanField()
    collection_id = IntegerField('Collection', validators=[Optional()])
    controller_support = BooleanField()
    date_added = HiddenField()
    date_modified = HiddenField()
    description = TextAreaField(validators=[Length(max=8192), Optional()])
    developer = StringField(validators=[Optional()])
    ESRB_RATINGS = [
        (None, 'None'),
        ('E', 'Everyone'),
        ('E10', 'Everyone 10+'),
        ('T', 'Teen'),
        ('M', 'Mature'),
        ('AO', 'Adults Only')
    ]
    esrb = SelectField('ESRB', choices=ESRB_RATINGS, validators=[Length(max=4), Optional()])
    favorite = BooleanField()
    filename = StringField('File Name', validators=[DataRequired('File Name required.'), Length(max=128)])
    genre_id = IntegerField('Genre', validators=[Optional()])
    gpu = StringField('GPU', validators=[Length(max=64), Optional()])
    hdd = StringField('HDD', validators=[Length(max=64), Optional()])
    mod = StringField('Mod/Engine', validators=[Length(max=64), Optional()])
    notes = TextAreaField(validators=[Length(max=8192), Optional()])
    online_multiplayer = BooleanField()
    operating_system = StringField(validators=[Length(max=64), Optional()])
    platform_id = IntegerField('Platform', validators=[DataRequired('Platform required.')])
    players = IntegerField('Player(s)', validators=[NumberRange(max=64), Optional()])
    processor = StringField('CPU', validators=[Length(max=64), Optional()])
    publisher = StringField(validators=[Length(max=128), Optional()])
    ram = StringField('RAM', validators=[Length(max=64), Optional()])
    REGIONS = [
        (None, 'None'),
        ('NA', 'North America'),
        ('EU', 'Europe'),
        ('JP', 'Japan'),
        ('SK', 'South Korea')
    ]
    region = SelectField(choices=REGIONS, validators=[Length(max=2), Optional()])
    save_path = StringField(validators=[Length(max=256), Optional()])

    steam_id = IntegerField(validators=[NumberRange(max=9999999), Optional()])
    STORE = [
        ('BLIZZARD', 'Blizzard'),
        ('GOG', 'GOG.com'),
        ('HUMBLE', 'Humble Bundle'),
        ('ITCH', 'itch.io'),
        ('PSN', 'PlayStation Network'),
        ('STEAM', 'Steam'),
        ('OTHER', 'Other')
    ]
    store = SelectField(choices=STORE, validators=[Length(max=64), Optional()])
    tags = StringField(validators=[Length(max=256), Optional()])
    title = StringField(validators=[DataRequired('Title required.'), Length(max=128)])
    translation = BooleanField()
    year = IntegerField(
        validators=[NumberRange(min=1940, max=2999, message='Year entered is out of sanity range.'), Optional()])
    submit = SubmitField("Save")


class CollectionForm(FlaskForm):
    name = StringField(validators=[Length(max=128)])
    description = TextAreaField(validators=[Length(max=4096), Optional()])
    submit = SubmitField("Save")

src/routes/app.py
from flask import Blueprint, send_from_directory
from lib.extensions import Config

app_bp = Blueprint('app', __name__)


@app_bp.route('/media/<path:path>')
def media(path):
    return send_from_directory(Config.MEDIA, path)


@app_bp.route('/json/<path:path>')
def json(path):
    return send_from_directory(Config.JSON, path)

src/routes/library.py
import base64
import datetime
import markdown
import os
import requests
import subprocess

from flask import Blueprint, flash, render_template, request, redirect, url_for
from lib.extensions import db, Config, Utils
from forms.library import CollectionForm, GameForm
from models.library import Collection, Game, Genre, Platform

library_bp = Blueprint('library', __name__)


# CONTEXT PROCESSORS
@library_bp.context_processor
def utility_processor():
    def debug_info():
        if Config.DEBUG:
            info = {}
            info.update({'app_title': Config.APP_TITLE})
            info.update({'debug': Config.DEBUG})
        else:
            info = None
        return info

    return {'debug_info': debug_info}


# ROUTES
@library_bp.route('/')
def home():
    # page = request.args.get('page', 1, type=int)
    pagination = Game.query.order_by(
        Game.date_added.desc()
    ).paginate(per_page=50, max_per_page=100)
    return render_template('library/home/index.html', pagination=pagination)


# GAMES
@library_bp.route('/library/game/new', methods=('GET', 'POST'))
def game_add():
    ga_collections = [
        (c.name, c.id) for c in Collection.query.order_by('name')]
    ga_genres = [(g.name, g.id) for g in Genre.query.order_by('name')]
    ga_platforms = [(p.name, p.id) for p in Platform.query.order_by('name')]
    form = GameForm()
    game = None
    if request.method == 'POST' and form.validate_on_submit():
        game = Game(
            archived=form.archived.data,
            co_op=form.co_op.data,
            collection_id=form.collection_id.data,
            controller_support=form.controller_support.data,
            description=form.description.data,
            developer=form.developer.data,
            esrb=form.esrb.data,
            favorite=form.favorite.data,
            filename=form.filename.data,
            genre_id=form.genre_id.data,
            gpu=form.gpu.data,
            hdd=form.hdd.data,
            mod=form.mod.data,
            notes=form.notes.data,
            online_multiplayer=form.online_multiplayer.data,
            operating_system=form.operating_system.data,
            platform_id=form.platform_id.data,
            players=form.players.data,
            processor=form.processor.data,
            publisher=form.publisher.data,
            ram=form.ram.data,
            region=form.region.data,
            save_path=form.save_path.data,
            steam_id=form.steam_id.data,
            store=form.store.data,
            tags=form.tags.data,
            title=form.title.data,
            translation=form.translation.data,
            year=form.year.data,
            date_added=datetime.datetime.now(),
            date_modified=datetime.datetime.now()
        )
        db.session.add(game)
        db.session.commit()
        flash('Game saved.')
    elif request.method == 'POST' and not form.validate_on_submit():
        flash('Could not save game.')
    return render_template(
        'library/game/add.html',
        collections=ga_collections,
        form=form,
        genres=ga_genres,
        game=game,
        platforms=ga_platforms)


@library_bp.route('/library/game/delete/<int:game_id>')
def game_delete(game_id):
    '''Remove game from database.

    Args:
        game_id (integer): Game ID
    '''
    try:
        # Game.query.filter(Game.id == game_id).delete()
        game = Game.query.get_or_404(game_id)
        db.session.delete(game)
        db.session.commit()
        flash('Game successfully deleted.')
    except Exception as e:
        flash('Error: game *not* deleted.')
        print(e)
    return redirect(url_for('library.home'))


@library_bp.route('/library/game/<int:game_id>')
def game_detail(game_id):
    game = Game.query.get_or_404(game_id)

    try:
        desc = markdown.markdown(game.description)
    except AttributeError:
        desc = None

    try:
        notes = markdown.markdown(game.notes)
    except AttributeError:
        notes = None

    platform = Platform.query.get_or_404(game.platform_id)
    file_path = Utils.get_filepath(platform.slug, game.filename)
    if os.path.exists(file_path):
        installed = True
    else:
        installed = False
    boxart_dir = Config.MEDIA + '/games/' + game.platform.slug + '/boxart/'
    boxart_file = game.slug() + '.jpg'
    boxart_url = boxart_dir + '/' + boxart_file
    if os.path.exists(boxart_url):
        boxart = boxart_url
    else:
        boxart = None

    return render_template(
        'library/game/detail.html',
        boxart=boxart,
        boxart_url=boxart_url,
        desc=desc,
        game=game,
        file_path=file_path,
        installed=installed,
        notes=notes)


@library_bp.route('/library/game/edit/<int:game_id>', methods=('GET', 'POST'))
def game_edit(game_id):
    game = Game.query.get_or_404(game_id)
    ge_collections = [
        (c.name, c.id) for c in Collection.query.order_by('name')]
    ge_genres = [(g.name, g.id) for g in Genre.query.order_by('name')]
    ge_platforms = [(p.name, p.id) for p in Platform.query.order_by('name')]

    form = GameForm()

    if request.method == 'POST' and form.validate_on_submit():
        if form.alt_title.data == 'None' or form.alt_title.data == '':
            game.alt_title = None
        else:
            game.alt_title = form.alt_title.data

        game.archived = form.archived.data
        game.co_op = form.co_op.data

        if form.collection_id.data == 0:
            game.collection_id = None
        else:
            game.collection_id = form.collection_id.data

        game.controller_support = form.controller_support.data

        if form.description.data == 'None':
            game.description = None
        else:
            game.description = form.description.data

        if game.developer == 'None':
            game.developer = None
        else:
            game.developer = form.developer.data

        if form.esrb.data == 'None':
            game.esrb = None
        else:
            game.esrb = form.esrb.data

        game.favorite = form.favorite.data
        game.filename = form.filename.data
        game.genre_id = form.genre_id.data

        if form.gpu.data == 'None':
            game.gpu = None
        else:
            game.gpu = form.gpu.data

        if form.hdd.data == 'None':
            game.hdd = None
        else:
            game.hdd = form.hdd.data

        if form.mod.data == 'None':
            game.mod = None
        else:
            game.mod = form.mod.data

        if form.notes.data == 'None':
            game.notes = None
        else:
            game.notes = form.notes.data

        game.online_multiplayer = form.online_multiplayer.data

        if form.operating_system.data == 'None':
            game.operating_system = None
        else:
            game.operating_system = form.operating_system.data

        game.platform_id = form.platform_id.data
        game.players = form.players.data

        if form.processor.data == 'None':
            game.processor = None
        else:
            game.processor = form.processor.data

        if form.publisher.data == 'None':
            game.publisher = None
        else:
            game.publisher = form.publisher.data

        if form.ram.data == 'None':
            game.ram = None
        else:
            game.ram = form.ram.data

        game.region = form.region.data

        if form.save_path.data == 'None':
            game.save_path = None
        else:
            game.save_path = form.save_path.data

        if form.steam_id.data == 'None':
            game.steam_id = None
        else:
            game.steam_id = form.steam_id.data

        if form.store.data == '':
            game.store = None
        else:
            game.store = form.store.data

        game.tags = form.tags.data
        game.title = form.title.data
        game.translation = form.translation.data
        game.year = form.year.data

        game.date_modified = datetime.datetime.now()

        db.session.commit()
        flash("Game data was saved.")
        return redirect(url_for('library.game_detail', game_id=game.id))
    elif request.method == 'POST' and not form.validate_on_submit():
        flash("Game data was *not* saved. Please check the log for errors.")
    return render_template('library/game/edit.html',
                           game=game,
                           collections=ge_collections,
                           genres=ge_genres,
                           form=form,
                           platforms=ge_platforms)


@library_bp.route('/library/game/<int:game_id>/readme')
def game_readme(game_id):
    game = Game.query.get_or_404(game_id)
    if game.description:
        description = markdown.markdown(game.description)
    else:
        description = None

    if game.notes:
        notes = markdown.markdown(game.notes)
    else:
        notes = None

    logo_dir = os.path.join(Config.MEDIA, 'games')
    logo_dir = os.path.join(logo_dir, game.platform.slug)
    logo_dir = os.path.join(logo_dir, 'logo')
    logo_file = game.slug() + '.png'
    logo_url = os.path.join(logo_dir, logo_file)

    if os.path.exists(logo_url):
        with open(logo_url, 'rb') as logo_file:
            logo_data = base64.b64encode(logo_file.read())
            logo = logo_data.decode('utf-8')
    else:
        logo = None

    return render_template(
        '/library/game/readme.html',
        game=game,
        description=description,
        logo=logo,
        notes=notes)


@library_bp.route('/library/game/favorites')
def favorites():
    pagination = Game.query.filter(Game.favorite).paginate(
        per_page=25,
        max_per_page=100)
    return render_template(
        '/library/game/favorites.html', pagination=pagination)


# Collections
@library_bp.route('/library/collections')
def collections():
    collections_index = Collection.query.order_by(Collection.name)
    return render_template(

src/templates/library/game/add.html
{% extends 'library/base.html' %}

{% block content %}

<h1 class="title">Add New Game</h1>

{% include 'library/game/form.html' %}

{% endblock %}


{% block sidebar %}

{% endblock %}

src/templates/library/game/detail.html
{% extends 'library/base.html' %}

{% block content %}

<div id="game-title">
    <h1>{% block title %}{{ game.sort_title() }}{% endblock %}</h1>
    {% if game.alt_title %}
        <div class="alt-title"><em>A.K.A. {{ game.alt_title }}</em></div>
    {% endif %}
</div>

<div id="game">
    <div id="boxart">
        {% if boxart %}
            <img src="{{ url_for('app.media', path='games/'+game.platform.slug+'/boxart/'+game.slug()+'.jpg') }}" alt="Boxart">
        {% else %}
            <span>boxart</span>
        {% endif %}
    </div>

    <div id="game_details">
        {% if game.esrb %}
            <div class="detail">
                <label>ESRB</label>
                <div>{{ game.esrb }}</div>
            </div>
        {% endif %}

        <div class="detail">
            <label>Players</label>
            <div>{{ game.players }}</div>
            {% if game.online_multiplayer %}
                <div>Online Multiplayer</div>
            {% endif %}
            {% if game.online_multiplayer %}
                <div>Co-op</div>
            {% endif %}
        </div>

        <div class="detail">
            <label>Controller</label>
            <div>
                {% if game.controller_support %}
                    Controller Supported
                {% else %}
                    Mouse/Keyboard Required
                {% endif %}
            </div>
        </div>

        <div class="detail">
            <label>Platform</label>
            <div><a href="{{ url_for('library.platform_detail', platform_id=game.platform.id) }}">{{ game.platform.name }}</a></div>
        </div>

        <div class="detail">
            <label>Year</label>
            <div>{{ game.year }}</div>
        </div>

        <div class="detail">
            <label>Region</label>
            <div>
                {{ game.region }}
                {% if game.translation %}
                    , <em>Translated</em>
                {% endif %}
            </div>
        </div>

        <div class="detail">
            <label>Genre</label>
            <div>{{ game.genre }}</div>
        </div>

        {% if game.tags %}
            <div class="detail">
                <label>Tags</label>
                <div>{{ game.tags }}</div>
            </div>
        {% endif %}

        <div class="detail">
            <label>Developer</label>
            <div>{{ game.developer }}</div>
        </div>

        <div class="detail">
            <label>Publisher</label>
            <div>{{ game.publisher }}</div>
        </div>

        {% if game.store %}
            <div class="detail">
                <label>Store</label>
                <div>{{ game.store }}</div>
            </div>
        {% endif %}

        {% if game.last_played %}
            <div class="detail">
                <label>Last Played</label>
                <div>{{ game.last_played.strftime('%Y-%m-%d') }}</div>
            </div>
        {% endif %}

        {% if game.play_count %}
            <div class="detail">
                <label>Play Count</label>
                <div>{{ game.play_count }}</div>
            </div>
        {% endif %}

        {% if game.collection_id %}
            <div class="detail">
                <label>Collection</label>
                <div>
                    <a href="{{ url_for('library.collection_detail', collection_id=game.collection_id) }}">{{ game.collection }}</a>
                </div>
            </div>
        {% endif %}

        {% if game.favorite %}
            <div class="detail">
                <label>Favorited &#x272d;<!--star unicode --></label>
            </div>
        {% endif %}

        {% if game.archived %}
        <div class="detail">
            <label>Archived &#x1f4bf;<!--disc unicode --></label>
        </div>
        {% endif %}

        {% if mc_score %}
        <div class="detail">
            <label>Metacritic Score</label>
            <div>{{ mc_score }}</div>
        </div>
        {% endif %}

        <div class="detail">
            <label>Date Added</label>
            <div>{{ game.date_added.strftime('%Y-%m-%d') }}</div>
        </div>

        <div class="detail">
            <label>Date Modified</label>
            <div>{{ game.date_added.strftime('%Y-%m-%d') }}</div>
        </div>
    </div>
</div>

<div>
    <div class="description">
        <h3>Description</h3>
        {{ desc | safe }}
    </div>

    <div id="tech-info">
        {% if game.operating_system %}
            <div id="system_requirements">
                <h3>System Requirements</h3>
                <table>
                    <tbody>
                        <tr>
                            <th>Operating System</th>
                            <td>{{ game.operating_system }}</td>
                        </tr>

                        <tr>
                            <th>Processor</th>
                            <td>{{ game.processor }}</td>
                        </tr>

                        <tr>
                            <th>Memory</th>
                            <td>{{ game.ram }}</td>
                        </tr>

                        <tr>
                            <th>Disk Space</th>
                            <td>{{ game.hdd }}</td>
                        </tr>

                        <tr>
                            <th>Graphics</th>
                            <td>{{ game.gpu }}</td>
                        </tr>

                        {% if game.mod %}
                            <tr>
                                <th>Mod/Engine</th>
                                <td>{{ game.mod }}</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        {% endif %}

        {% if notes %}
            <div class="notes">
                <h3>Notes</h3>
                {{ notes | safe }}
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block sidebar %}
    <h4>Launch Game</h4>
    
    {% if installed %}
        <div class="launcher">
            <button class="execute" onClick="launch_game('{{ game.platform.slug }}','{{ game.filename }}' )">
                <img src="{{ url_for('static', filename='assets/img/icons/play.svg')}}"/> Play
            </button>
        </div>
    {% endif %}

    <h4>Links</h4>
    <p>
        <a href="https://www.giantbomb.com/search/?i=game&q={{ game.title }}">
            <img class="icon" src="{{ url_for('static', filename='assets/img/icons/giantbomb.svg') }}" title="Giant Bomb"></a>

        <a href="https://www.mobygames.com/search/quick?q={{ game.title }}">
            <img class="icon" src="{{ url_for('static', filename='assets/img/icons/moby.svg') }}" title="Moby Games"></a>

        <a href="https://thegamesdb.net/search.php?name={{ game.title }}">
            <img class="icon" src="{{ url_for('static', filename='assets/img/icons/tgdb.svg') }}" title="TGDB"></a>
            
        {% if game.platform.slug == 'windows' or game.platform.slug == 'steam' or game.platform == 'linux' %}
            <a href="https://www.pcgamingwiki.com/w/index.php?search={{ game.title }}">
                <img class="icon" src="{{ url_for('static', filename='assets/img/icons/pcgw.svg') }}" title="PCGamingWiki"></a>
                {% if game.platform.slug == 'steam' %}
                    <a href="https://www.protondb.com/app/{{ game.filename }}">
                        <img class="icon" src="{{ url_for('static', filename='assets/img/icons/protondb.svg') }}" title="ProtonDB"></a>

                    <a href="https://steamdb.info/app/{{ game.filename }}">
                        <img class="icon" src="{{ url_for('static', filename='assets/img/icons/steamdb.svg') }}" title="SteamDB"></a>
                {% else %}
                    <a href="https://www.protondb.com/search?q={{ game.title }}&type=1&category=0">
                        <img class="icon" src="{{ url_for('static', filename='assets/img/icons/protondb.svg') }}" title="ProtonDB"></a>

                    <a href="https://steamdb.info/search/?a=app&q={{ game.title }}&type=1&category=0">
                        <img class="icon" src="{{ url_for('static', filename='assets/img/icons/steamdb.svg') }}" title="SteamDB"></a>
            {% endif %}
        {% endif %}
    </p>

    <ul>
        <li><a href="{{ url_for('library.game_edit', game_id=game.id) }}">EDIT</a></li>
    </ul>

    <div class="data-fields">
        <label>Debug</label>
        <ul>
            <li><b>filename: </b><span id="filename">{{ game.filename }}</span></li>
            <li><b>platform_slug: </b><span  id="platform_slug">{{ game.platform.slug }}</span></li>
            <li><b>file_path: </b><span  id="file_path">{{ file_path }}</span></li>
            <li id="save_path"><b>save_path: </b>{{ game.save_path }}</li>
            <li id="boxart_url"><b>boxart_url: </b>{{ boxart_url }}</li>
        </ul>
    </div>
{% endblock %}

src/templates/library/game/edit.html
{% extends 'library/base.html' %}

{% block content %}

<h1 class="title">{% block title %} Edit {{ game.title }} {% endblock %}</h1>

<form method="post">
    {{ form.hidden_tag() }}
    <div class="field">
        {{ form.title.label }}<br>
        {{ form.title(class="title", value=game.title) }}
    </div>

    <div class="field">
        {{ form.description.label }}<br>
        <textarea class="description" id="description" name="description" value="test">{{ game.description }}</textarea>
    </div>

    <div class="field">
        {{ form.year.label }}<br>
        {{ form.year(class="year", value=game.year) }}
    </div>

    <div class="field">
        <label>Genre</label><br>
        <select name="genre_id" id="genre_id">
            <option value=None>None</option>

            {% for name, id in genres %}
                <option value="{{ id }}"
                    {% if id  == game.genre.id %}
                        selected
                    {% endif %}>
                    {{ name }}
                </option>
            {% endfor %}

        </select>
    </div>

    

<!--     <div class="field">
        <label>Description</label>
        <textarea
            name="description"
            placeholder="Enter description here..."
            cols="60" rows="5">
            {{ game.description }}
        </textarea>
    </div> -->

    <div>{{ form.submit() }}</div>
</form>

{% endblock %}


{% block sidebar %}

{% if installed %}
    <div>
        Installed to <span id="game_path">{{ game_path }}</span>
    </div>
    <div class="launcher">
        <button onClick="launch_game()">Launcher</button>
    </div>
{% endif %}





{% endblock %}

src/templates/library/game/favorites.html
{% extends 'library/base.html' %}

{% block content %}

<h1 class="title">{% block title %} Favorites {% endblock %}</h1>

{% include 'library/game/list.html' %}

{% endblock %}

src/templates/library/game/list.html
<table class="game-list">
    <thead>
        <tr>
            <th>Title</th>
            <th>Platform</th>
            <th>Genre</th>
            <th>Year</th>
            <th>Rating</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        {% for game in pagination.items %}
            <tr>
                <td>
                    <a href="{{ url_for('library.game_detail', game_id=game.id) }}">{{ game.title }}</a>
                    {% if game.alt_title %}<br>
                        <em class="alt_title">a.k.a. {{ game.alt_title }}</em>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('library.platform_detail', platform_id=game.platform_id) }}">{{ game.platform }}</a>
                </td>
                <td>
                    <a href="">{{ game.genre }}</a>
                </td>
                <td>
                    {{ game.year }}
                </td>
                <td>{{ game.esrb }}</td>
                <td>
                    <a href="{{ url_for('library.game_edit', game_id=game.id) }}">Edit</a>
                    <a href="{{ url_for('library.game_delete', game_id=game.id) }}">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="100%">
                {% if pagination.pages > 1 %}
                    <div class="pagination">
                        {% if pagination.has_prev %}
                            <span>
                                <a class='page-number' href="{{ url_for('library.home', page=pagination.prev_num) }}">
                                    {{ '<<<' }}
                                </a>
                            </span>
                        {% endif %}

                        {% for number in pagination.iter_pages() %}
                            {% if pagination.page != number %}
                                <span>
                                    <a class="page-number" href="{{ request.path }}?page={{ number }}">
                                        {{ number }}
                                    </a>
                                </span>
                            {% else %}
                                <span class='current-page-number'>{{ number }}</span>
                            {% endif %}
                        {% endfor %}

                        {% if pagination.has_next %}
                            <span>
                                <a class="page-number" href="{{ request.path }}?page={{ pagination.next_num }}">
                                    {{ '>>>' }}
                                </a>
                            </span>
                        {% endif %}
                    </div>
                {% endif %}
            </td>
        </tr>
    </tfoot>
</table>